#!/bin/bash

set -eo pipefail

echo "[nginx] booting container."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $M1 -node $M2 -node $M3 -config-file /etc/confd/conf.d/nginx.toml; do
    echo "[nginx] waiting for confd to create initial nginx configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
#confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/nginx.toml &
confd -interval 10 -node $M1 -node $M2 -node $M3 -config-file /etc/confd/conf.d/nginx.toml &
echo "[nginx] confd is now monitoring etcd for changes..."

# Start the Nginx service using the generated config
echo "[nginx] starting nginx service..."
service nginx start

# Follow the logs to allow the script to continue running
tail -f /var/log/nginx/*.log
